commclassroom/classroom-monitor-bot

.github/workflows/labels.yml

Labeling feature enabled for dev branch.

fix: :wrench: Fixed Labeling action

---

config.json

This PR fixes the following issues : #16 
#example
Changed prefix to cm

Change prefix to cm

---

.github/workflows/greetings.yml

This PR fixes the following issues : Updated Discord Link In Greeting Action.

 fix: 📝Updated Discord Link 

---

Commands/help.js
Commands/hey.js
Commands/links.js
Commands/restrictedWords.js

This PR fixes the following issues :
#example
Gone through the bot commands and changed wherever cc is written with cm.

fix: :hammer: Relative cc initials changed to cm

---

Commands/restrictedWords.js

This PR fixes the following issues :
Delete author's message after warning them

feat: added command to delete user's message after warning

---

README.md

This PR fixes the following issues :
Typo on README.md

Fixing broken image link on README.md - 1

---

Commands/presence.js
index.js

This PR fixes the following issues :
Added a Status/Activity for the Bot (LISTENING to cm!help)

[Feature] Added Bot Status 

---

.github/pull_request_template.md

This PR fixes the following issues: #39 
#example

Fixed typos and grammatical mistakes.

---

README.md

This PR fixes the following issues : #33 
#example
* Divided commit message to `commit message format` and `Creating commits`
* Commit message format contains the basic format for commit.
* Creating commits contains an example and some tips for writing good commit message

Update Readme with commit example

---

Commands/presence.js
index.js

* feat: 🚀 Added Bot Status/Activity
* feat: 🚀 Added Bot Status/Activity
* fix: 🔧 fixed repeating word.
* fix: 🔧 Updated the Identation of Code.
#example

[Feature] Added Bot Status  (#34)

---

.github/workflows/greetings.yml
CONTRIBUTING.md
Commands/links.js
README.md

Here comes all the changes proposed through this PR : 
Replaced the old Discord URL with the New Vanity URL which we recently got.

[FIX] : Updated the Old Discord Link to Vanity URL 

---

Commands/help.js
Commands/translate.js
README.md
index.js
package-lock.json
package.json

#64 
I used a third party package called bing-translate-api to do the translations. It automatically detects the written language and translates it to English. We can use this feature by writing cm!translate [TEXT] and it's going to translate it.
**IMPORTANT NOTE:** The package bing-translate-api needs a little tweaking after installation. I already sent a pull request to the maintainer and he approved but I don't know if it's updated in NPM so we need to go to node_modules/bing-translate-api/src/lang.js and then do this change before deploying the bot.

Translation

---

Commands/help.js
Commands/meme.js
README.md
index.js
package-lock.json
package.json

#66 
Added cm!meme command which sends a post titlte and post image from r/programmerhumor

Added cm!meme command

---

Commands/source.js
index.js

feat: ✨ Added `source` command!

---

Commands/DSA.js
Commands/help.js
Commands/hey.js
Commands/links.js
Commands/meme.js
Commands/source.js
Commands/translate.js
Commands/version.js
index.js
package-lock.json
package.json

Here are the screenshots...
Help command :-
https://tanshadow.is-inside.me/1OOa4wAy.png
Hey command :-
https://tanshadow.is-inside.me/gsmEDKwO.png
Version command :-
https://tanshadow.is-inside.me/pivOCiLm.png
Links command :-
https://tanshadow.is-inside.me/P2dXk8Rj.png
Translate command :-
( without args ) -> https://tanshadow.is-inside.me/OAHLvQcp.png
( with args ) -> https://tanshadow.is-inside.me/AkX6Bi00.png
Meme command :- 
https://tanshadow.is-inside.me/9W1vBM3v.png
Source command :-
https://tanshadow.is-inside.me/W4q7h6N9.png
DSA command :-
https://tanshadow.is-inside.me/F76UlA7J.png
Commands don't work in dms :-
https://tanshadow.is-inside.me/WMPZVYgx.png
Restricted words :- …

refactor: :sparkles: Refactored the codebase

---

Commands/restrictedWords.js

#13
Added a array of curse words. Bot scans the messages if any of them contain a word from the array.
Here are some tests

feat: ✨ add curse word detection

---

README.md

This PR fixes the following issues: #80 
Here comes all the changes proposed through this PR - Fixed small typo in the README file

Fix : Fixed Small typo in README file

---

Commands/restrictedWords.js
config.json
package-lock.json
package.json

feat: alexjs

---

Commands/restrictedWords.js

Closes #88 
Fixed `Classroon monitor`

fix: :rocket: Typo

---

CODE_OF_CONDUCT.md

- Update the Code of Conduct to the latest version.

docs: Update the Code of Conduct to the latest version

---

config.json

- Add some non-profane words to the config file.
- Closes #99.

fix: Add some non-profane words to the config file

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/other.yml

- Disable blank issues and add a generic template.

feat: Disable blank issues and add a generic template

---

.github/workflows/greetings.yml

- Fix the Discord link in the `greetings.yml` workflow.

fix: Discord link in the `greetings.yml` workflow

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/doc_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

- Fix the labels in the issue templates.

fix: labels in the issue templates

---

README.md

- Improve the `README.md` file.
- Improves grammar, fixes some spelling typos, and fixes a lot of Markdown linter issues.

[docs/fix]: Improve the `README.md` file

---

.github/pull_request_template.md

- Improve the pull request template.

docs: Improve the pull request template

---

config.json

fix: 🛠 Added Japanese, Chinese, American to allowed list

---

README.md

- Update the Discord logo to the latest version.

fix: Update the Discord logo to the latest version

---

config.json

- Add more words to the whitelist.
- All these words have been taken from Discord.

fix: Add more words to the whitelist

---

docs/index.md

- Improve the `index.md` file.

docs: Improve the `index.md` file

---

.github/workflows/greetings.yml

- Use `pull_request_target` in the greetings workflow.
- This would be the best way for this workflow to run (see https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target for more information)

fix: use `pull_request_target` in the greetings workflow

---

README.md

- Make the Community Classroom logo transparent.
- This will make the logo look fine for dark mode users.

feat: Make the Community Classroom logo transparent

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/greetings.yml
README.md
docs/CONTRIBUTING.md
docs/index.md

- Update the invitation link to use `discord.gg`.

fix: update invitation link to use `discord.gg`

---

.github/workflows/greetings.yml

- Improve the greetings workflow text.

chore: improve the greetings workflow text

---

docs/index.md

- Fix the Discord logo link (again).
- The link was pointing to a branch that has been deleted now. 😅

fix: Discord logo link (again)

---

docs/CONTRIBUTING.md

- Fix issue templates links in the contributing file.

fix: issue templates links in the contributing file

---

Commands/DSA.js
Commands/help.js
Commands/links.js
Commands/presence.js
Commands/restrictedWords.js
Commands/source.js
LICENSE
README.md
docs/CONTRIBUTING.md
docs/commands/help.md
docs/commands/hey.md
docs/commands/links.md
docs/commands/meme.md
docs/commands/translate.md
docs/commands/version.md
docs/index.html
docs/index.md
package.json

- Update all links to point to Community Classroom organization.

fix: Update all links to point to Community Classroom

---

docs/index.html

feat: Improve SEO

---

config.json

fix: add more words to the list

---

Commands/restrictedWords.js

- Add more Nitro scam definitions.

fix: add more Nitro scam definitions

---

config.json

- Add `remain` to the whitelist
- Closes #132 

fix: add remain to the whitelist

---

Commands/translate.js

Closes #135 
Removed the error reply by the bot - "Cannot understand certain language"
Not required | Not required |

Removed the error reply by the CM bot

---

Commands/translate.js

- Short the code: remove/fix unused `if` sentence.

fix: remove unused `if` sentence

---

config.json

Added 'hook' to the list to be allowed.
Fixes Issue #139

fix: add `hook` to the list

---

README.md

Fix: Fixed some typo in README file

---

src/Commands/restrictedWords.js

- Using `const` instead of `let`.
- Changed the file `src/Commands/restrictedWords.js` for now. But if approved, I will fix all errors if there are more.
- Closes #147 

fix: use `const` instead of `let`

---

src/Commands/links.js

- Fix the Discord invitation link.

fix: Discord invitation link

---

src/Commands/restrictedWords.js

- Added `edtech startups` in restricted words.
- Added multiple entries of the words so it can't be used in the channels/server.
- Fixes #106 

feat: restrict edtech startups

---

config.json

The word "uk" is added to white list .
Closes #151 

chore: add the `uk` word to the whitelist

---

docs/CONTRIBUTING.md

Corrected a typo. @kaiwalyakoparkar @siddhant-khisty Please review.
Fixed a typo
- [x ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

Corrected documentation typo in CONTRIBUTING.md
